### ISSUE TITLE
Build Issue, can't build successfully.

### ISSUE THREAD

**Issue by sentiasa** [eface2face/iosrtc-apprtc#1]
Hi, I have installed cordova 5.1.1 and tried to build the demo as it is showed. I did:
$ cordova platform add ios
$ cordova plugin add com.eface2face.iosrtc
$ cordova build

It gets completed and I run the xCode project in platforms/ios/... First, as it is originally set to Deployment Target: 6.0, it gives me an error (1 error):

> Check dependencies 
> Swift is unavailable on iOS earlier than 7.0; please set IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '6.0').

Then, I changed Deployment Target to iOS 7.0, hovever, this time, I ended up with 217 errors, mainly on:

> 'Use of unresolved identifier ...' 
> 'Use of undeclared type ...' (for almost everything)
> '... does not have a member named ...'

Am I doing something wrong? I tried it multiple times but no luck at all.

Thanks in advance

**Comment by jesusprubio** [comment]
Hi, does this work for you?
![captura de pantalla 2015-06-16 a las 11 58 17](https://cloud.githubusercontent.com/assets/2753855/8180568/1fcc72c8-141f-11e5-8016-ba6c77120b5c.png)
![captura de pantalla 2015-06-16 a las 11 58 28](https://cloud.githubusercontent.com/assets/2753855/8180569/1fcf9c46-141f-11e5-8a47-198865a5fa53.png)

If it's working try to remove the ios platform (or even the "platforms" folder directly) and start again from scratch with your code.

**Comment by ibc** [comment]
There is extensive documentation in the **cordova-plugin-iosrtc** about how to build an app with the plugin and XCode. Please read it:
- https://github.com/eface2face/cordova-plugin-iosrtc#building
- https://github.com/eface2face/cordova-plugin-iosrtc/blob/master/docs/Building.md

**Comment by ibc** [comment]
If you compile/build the app with Cordova and then run the app with XCode, ugly things may happen. Just avoid that.
