### ISSUE TITLE
Swift 2.1 Support

### ISSUE THREAD

**Issue by taylorlc70** [eface2face/iosrtc-apprtc#11]
Despite using the new BUILD documentation (which we have been doing for a while now), the iosrtc plugin now fails to compile.

The following build commands failed:
CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/iosrtcPlugin.swift
CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginRTCTypes.swift
CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginRTCPeerConnection.swift
CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginRTCDataChannel.swift
CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginMediaStreamTrack.swift
CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginMediaStreamRenderer.swift
CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(7 failures)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/cordova/build-debug.xcconfig,-project,ustyme.xcodeproj,ARCHS=i386,-target,ustyme,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/cordova/build: Command failed with exit code 2

Looks like Swift upgraded again (2.1). There are several compilation errors using XCode 7.1. I tried to use the automatic syntax converter to change to latest syntax, but I was still left with several errors (for some reason the auto-syntax change likes to try to change variable names). Specifically, there are now errors with:
- some force unwrapping issues
- try/catch blocks - must catch all undefined errors with a generic catch
- AnyObject in dictionaries (type casting as NSDictionary seems to work)
- Using @objc for objects that do not inherit directly from NSObject

though that is with my very limited Swift experience.

**Comment by ibc** [comment]
Please, don't report here issues about cordova-plugin-iosrtc. It has its own Github project. Anyhow, the upgrade to Swift 2.1 was already done weeks ago.
