### ISSUE TITLE
iOSRTCApp Possible issue

### ISSUE THREAD

**Issue by gabri15** [eface2face/iosrtc-apprtc#12]
Author, can you test this case, please?

First with a simple browser in the computer side (Chrome, Firefox) go to https://apprtc.appspot.com/ .
After that, enter in a single room.

Then run iOSRTCApp in a mobile phone and try to enter in the room, nothing happens, you can not see the video and the audio  in both sides.
I was researching all afternoon, checking logs in Android Studio, Xcode, but i can't find the problem.

If you try to make (Smartphone)iOSRTCApp ----apprtc---------iOSRTCApp (Smarphone) will replay  the same error.

I hope that this information will be useful for you.

Other questions:

It possible to draw a simple button to make a hang up button?
When the user leave the room, the iOSRTCApp can handle this event?

Thanks !!

**Comment by ibc** [comment]
I'm sorry but I do not support this demo application anymore. It is just a demo app of the cordova-plugin-iosrtc, nothing else.
