### ISSUE TITLE
Video stream freezes on iPad 3

### ISSUE THREAD

**Issue by derwaldgeist** [eface2face/iosrtc-apprtc#13]
I've tried this library on my (old) iPad 3 and my (rather new) HTC One, both with a web-browser counterpart using AppRTC, using your sample app. On the HTC, everything worked fine.

But with my iPad, the remote video stream froze after some seconds, on both the iPad (i.e. the browser stream viewed on the iPad) and the browser (i.e. the iPad stream viewed on the browser).

What may cause this?

With the (quite old and unmaintained) OpenTok Cordova plugin, I do not have these freezing issues. But I would like to switch to a provider-independent, up-to-date version, so I am evaluating the eface2face solution as an alternative Cordova implementation (it's the only maintained solution as far as I can tell, so thanks for doing this!).

PS: On both Android and iOS, the video does not adjust to screen orientation changes. Is this a limitation in the framework, or just a limitation of your sample app?

**Comment by ibc** [comment]
This is just a demo app and I do not support it. If you find a reproducible issue please report at the cordova-plugin-iosrtc project.
