### ISSUE TITLE
Build process broken

### ISSUE THREAD

**Issue by matthias62** [eface2face/iosrtc-apprtc#14]
Hello,

I cannot build iOSRTCApp on ios. I use Xcode 7.2. 

I follow your instructions. When I call "cordova platform add ios" I get the error:

"iosrtc-swift-support.js [ERROR] an error occurred during the parsing of the project file"

If I do after that "cordova platform remove ios" and add it anew I get a different error message:

"Failed to install cordova-plugin-whitelist. Error: Variable(s) missing ..."

If I ignore that an try to build the xcode project nevertheless by loading it with xcode I get lots of "unresolved identifier" compiler errors - probably because of problems whith the bridging header. 

Not sure whether that could be the cause:

When I do the "npm install" I get warnings:

"engine ... wanted node 0.8x ..." current: 4.2.2
"depracated lodash-node: package no longer maintained"

I cloned your project and implemented some own functionality but my own project does of course show the same problems as your original when trying to build it now. The last successful build I did was at the the beginning of December. There I did not have problems.

Thank you for your advice.

**Comment by ibc** [comment]
Sorry, this is just an unmaintained usage example of the cordova-plugin-iosrtc.
