### ISSUE TITLE
run then crashed in iPhone5s with iOS 9.2

### ISSUE THREAD

**Issue by hgz07** [eface2face/iosrtc-apprtc#15]
while crashed,  xcode debug output:
dyld: Library not loaded: @rpath/GCDWebServer.framework/GCDWebServer
  Referenced from: /var/mobile/Containers/Bundle/Application/B01E17BD-180B-4260-9654-04DDAB17D93C/iOSRTCApp.app/iOSRTCApp
  Reason: image not found

**Comment by ibc** [comment]
It seems an usage problem.

**Comment by hgz07** [comment]
and details ?

**Comment by ibc** [comment]
No. It is just that this is not the forum of any Cordova+iOS related problem. `cordova-plugin-iosrtc` does not use such a `GCDWebServer` at all. If that is part of Cordova+iOS then that is not a bug in this plugin.

**Comment by hgz07** [comment]
I found its solution----- I remove the external frameworks named GCDWebServer and XWalkerView.framework.  
iOSRTCApp run normally.

**Comment by hgz07** [comment]
But after run up iOSRTCApp, I see the html error :  
  Uncaught TypeError : can not read property 'platform' of undefined.
in appwindows.html  Line 133:
   if (window.device.platform === "iOS") {

**Comment by ibc** [comment]
This is the project bug-tracker. Please ask your doubts and questions in the project public mailing list (unless you really find a bug).

**Comment by hgz07** [comment]
ok

**Comment by hgz07** [comment]
find :    window.device  is  undefined.
It appears repeatly.

**Comment by ibc** [comment]
Yes, that's because you copy&pasted the example code without reading it:

> (assuming that cordova-plugin-device is installed)
