### ISSUE TITLE
Unable to compile on Xcode 7.2

### ISSUE THREAD

**Issue by azachar** [eface2face/iosrtc-apprtc#16]
Hello, 

I have a hard time to compile the plugin, here is the exception I having with target platform 7.0

`/cordova-plugin-iosrtc/iosrtcPlugin.swift:5:2: **Only classes that inherit from NSObject can be declared @objc`

Thanks

**Comment by azachar** [comment]
You need to modify config.xml 

`<engine name="ios" spec="~3.9.2" />`

that is all.

**Comment by ibc** [comment]
Nice :)
