### ISSUE TITLE
Black screen on android

### ISSUE THREAD

**Issue by ramsestom** [eface2face/iosrtc-apprtc#17]
Tested it on android but the video do not display. 
I had an error in the output console:
"Refused to load media "blob:xxxx" because it violates the following Content Security Policy directive: "media-src *".
That I fixed by setting  "media-src \* blob:" (instead of " media-src *") in the "Content-Security-Policy" tag of appwindow.html.
Now I don't have any error reported in the chrome remote debugger console but the video still do not appear (the screen remains black when connected to a room, with a message saying that there is no TURN server (but as I test between two instances in the same local network, don't think it is the issue. And I should at least see the video of my own device anyway))
Anyone experienced the same issue before?

**Comment by ibc** [comment]
This is a demo of cordova-plugin-iosrtc, this is, just for iOS. And it is not actively maintained because it's just a demo. The README says that.

**Comment by ramsestom** [comment]
The blog article says it is for ios AND android: https://webrtchacks.com/webrtc-hybrid-applications/
Same for the README file:
Add both platforms. All the needed plugins are installed automatically because of being included in the "config.xml" file:
$ cordova platform add ios android

**Comment by ibc** [comment]
It is a demo app, nothing else.

**Comment by ramsestom** [comment]
I know that. but according to your post: https://webrtchacks.com/webrtc-hybrid-applications it is supposed to be a demo app that works on both android and ios. I didn't succed to make it work on android (not tested on ios) and it is the only demo of a cordova app using native webrtc (not the phonertc plugin) that I found on the web. So I am trying to make it work ;)
If you have the code of another cordova webrtc app working on android, I will take it too

**Comment by ibc** [comment]
I understand. However I'm sorry but I cannot spend time on that.
