### ISSUE TITLE
cannot build ios app

### ISSUE THREAD

**Issue by iwan-uschka** [eface2face/iosrtc-apprtc#19]
hey there,
just tried to run your example app, but built process failed.

xcode 8.2
cordova 6.4.0

"Cordova/NSData+Base64.h" not found
thanks

**Comment by ibc** [comment]
Sorry, this is an unmaintained demo app which does not even depend on the last version of the plugin.

**Comment by iwan-uschka** [comment]
yes, saw that. thanks for answering anyway. hope to get iosrtc working in my project and resolve swift version issues
