### ISSUE TITLE
Cannot find getUserMedia on ios emulator

### ISSUE THREAD

**Issue by okpatil4u** [eface2face/iosrtc-apprtc#2]
Hi, I am getting these errors on ios 5 emulator.
![ios simulator screen shot 19 jun 2015 8 40 44 pm](https://cloud.githubusercontent.com/assets/3041904/8251890/bea26ef6-16c3-11e5-961b-86f99ffc19c3.png)
![ios simulator screen shot 19 jun 2015 8 40 51 pm](https://cloud.githubusercontent.com/assets/3041904/8251891/bea4c39a-16c3-11e5-84c2-2ac231847e5c.png)

**Comment by ibc** [comment]
Of course. The iPhone Simulator in OSX has no access to the mic/webcam devices.
