### ISSUE TITLE
Signalling

### ISSUE THREAD

**Issue by drakula84** [eface2face/iosrtc-apprtc#4]
Great work! I have a question though..

Signalling is not really an issue with the code but I am trying to figure out what is the best way to implement the signalling between peers to carry the SDP for iOS (and Android). WebSocket would not always work when the application is at background or not running. Push Notifications come into play in that case but is there any API out there that you use or know that handles the scenarios (fallback to Push if necessary) for a WhatsApp/Viber like application?

**Comment by ibc** [comment]
Hi @drakula84. This is not the place to discuss about proper signaling mechanisms for Android/iOS apps, even if they are Cordova based apps.
