### ISSUE TITLE
Issue With the Command "cordova platform add ios android"

### ISSUE THREAD

**Issue by excendia** [eface2face/iosrtc-apprtc#5]
cordova platform add ios android
Adding ios project...
iOS project created with cordova-ios@3.8.0
Installing "cordova-plugin-camera" for ios
Installing "cordova-plugin-crosswalk-webview" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-iosrtc" for ios

```
    cordova-plugin-iosrtc enables use of the JavaScript WebRTC APIs (as defined by the W3C) in iOS devices.
    Learn more at: https://github.com/eface2face/cordova-plugin-iosrtc
```

Installing "cordova-plugin-whitelist" for ios
npm http GET https://registry.npmjs.org/cordova-android
npm http 304 https://registry.npmjs.org/cordova-android
Adding android project...
Creating Cordova project for the Android platform:
    Path: platforms/android
    Package: com.eface2face.iosrtcapp
    Name: iOSRTCApp
    Activity: MainActivity
    Android target: android-22
Copying template files...
Android project created with cordova-android@4.0.2
Installing "cordova-plugin-camera" for android
Installing "cordova-plugin-crosswalk-webview" for android
Installing "cordova-plugin-device" for android
Installing "cordova-plugin-iosrtc" for android

```
    cordova-plugin-iosrtc enables use of the JavaScript WebRTC APIs (as defined by the W3C) in iOS devices.
    Learn more at: https://github.com/eface2face/cordova-plugin-iosrtc
```

Installing "cordova-plugin-whitelist" for android
Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Excendia/iOSRTCApp/hooks/iosrtc-swift-support.js:10:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by ibc** [comment]
Please, open a new issue if the same problem happens when adding "ios platform" instead of "android" (given that this plugin is NOT for android but just for ios).

**Comment by ibc** [comment]
Sorry, I thought this issue was reported into the cordova-plugin-iosrtc project. Deleting my useless comments.

**Comment by ibc** [comment]
BTW the [Building](https://github.com/eface2face/cordova-plugin-iosrtc/blob/master/docs/Building.md) documentation of _cordova-plugin-iosrtc_ clearly states that _xcode_ NPM package is required.

**Comment by ibc** [comment]
I've updated the README to mention that xcode NPM package is required: 77b92a84faf30437e2ef9b90a596a772435264ce

**Comment by celevra** [comment]
hi,

i get the error with installed xcode

```
hilipp@air ~/ifolder/code/keenmeet $ sudo npm install -g xcode
xcode@0.8.0 /usr/local/lib/node_modules/xcode
├── node-uuid@1.3.3
└── pegjs@0.6.2
philipp@air ~/ifolder/code/keenmeet $ cordova platform remove ios
philipp@air ~/ifolder/code/keenmeet $ cordova platform add ios
Adding ios project...
iOS project created with cordova-ios@3.9.1
Installing "cordova-plugin-console" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-iosrtc" for ios

        cordova-plugin-iosrtc enables use of the JavaScript WebRTC APIs (as defined by the W3C) in iOS devices.
        Learn more at https://github.com/eface2face/cordova-plugin-iosrtc

Installing "cordova-plugin-whitelist" for ios
Error: Cannot find module 'xcode'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/philipp/ifolder/code/keenmeet/hooks/iosrtc-swift-support.js:10:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
philipp@air ~/ifolder/code/keenmeet $
```

installing xcode only locally not with -g worked for me

**Comment by ibc** [comment]
> installing xcode only locally not with -g worked for me

Right. Not sure why but it works. I've updated the README and added a NPM package.json file to the project, so the user must run `npm install` (then `xcode` package is installed and build works).

**Comment by sureshkoduri** [comment]
I have the same issue. Please help

**Comment by ibc** [comment]
It is fixed in master. Please read the comment above, not so hard.

**Comment by f18nfz** [comment]
Had the same issue, and the suggested fixes didn't work. So I just deleted the .cordova folder in C:\Users\(yourusername) and this resolved the issue for me, looks like a cache issue from upgrading stuff

**Comment by manuellucas101976** [comment]
Do you mean the first folder you have created? I am using Ubuntu.
