### ISSUE TITLE
iOS -> iOS not working

### ISSUE THREAD

**Issue by bart-jansen** [eface2face/iosrtc-apprtc#6]
Both iOS -> AppRTC and AppRTC -> AppRTC are working fine. But can't seem to get an established connection between 2 iOS devices working. 

Connection doesn't seem to get established and continuous 'Waiting for another person to join the room' message appears.

Did someone else get this working?

**Comment by ibc** [comment]
It seems that rooms can only be created from the web app, maybe due the Origin header. Nothing we can do. Anyhow this is just a demo.
