### ISSUE TITLE
iOS 9 compilation error

### ISSUE THREAD

**Issue by adam-ski** [eface2face/iosrtc-apprtc#9]
The issue has been described here 
http://stackoverflow.com/questions/32472577/cordova-iosrtc-complie-error

I getting quite similar error
The following build commands failed:
    CompileSwift normal i386 /Users/adamactivate/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/iosrtcPlugin.swift
    CompileSwift normal i386 /Users/adamactivate/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/PluginRTCTypes.swift
    CompileSwift normal i386 /Users/adamactivate/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/PluginRTCPeerConnection.swift
    CompileSwift normal i386 /Users/adamactivate/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/PluginRTCDataChannel.swift
    CompileSwift normal i386 /Users/adamactivate/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/PluginMediaStreamTrack.swift
    CompileSwift normal i386 /Users/adamactivate/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/PluginMediaStreamRenderer.swift
    CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(7 failures)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/adamactivate/iOSRTCApp/platforms/ios/cordova/build-debug.xcconfig,-project,iOSRTCApp.xcodeproj,ARCHS=i386,-target,iOSRTCApp,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/adamactivate/iOSRTCApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/adamactivate/iOSRTCApp/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/adamactivate/iOSRTCApp/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/adamactivate/iOSRTCApp/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Process.ChildProcess._handle.onexit (child_process.js:820:5)

**Comment by xelven** [comment]
me too, same problem:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal i386 /Users/allenchan/WorkStation/iOS/testiOSRTCApp/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/iosrtcPlugin.swift
    CompileSwift normal i386 /Users/allenchan/WorkStation/iOS/testiOSRTCApp/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/PluginRTCTypes.swift
    CompileSwift normal i386 /Users/allenchan/WorkStation/iOS/testiOSRTCApp/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/PluginRTCPeerConnection.swift
    CompileSwift normal i386 /Users/allenchan/WorkStation/iOS/testiOSRTCApp/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-iosrtc/PluginRTCDataChannel.swift
    CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(5 failures)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/allenchan/WorkStation/iOS/testiOSRTCApp/iOSRTCApp/platforms/ios/cordova/build-debug.xcconfig,-project,iOSRTCApp.xcodeproj,ARCHS=i386,-target,iOSRTCApp,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/allenchan/WorkStation/iOS/testiOSRTCApp/iOSRTCApp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/allenchan/WorkStation/iOS/testiOSRTCApp/iOSRTCApp/platforms/ios/build/sharedpch
ERROR running one or more of the platforms: Error: /Users/allenchan/WorkStation/iOS/testiOSRTCApp/iOSRTCApp/platforms/ios/cordova/run: Command failed with exit code 2

**Comment by ibc** [comment]
Sorry, I don't have time for supporting this demo app. Please check the cordova-plugin-iosrtc BUILDING documentation.

**Comment by taylorlc70** [comment]
We have been using this plugin for a while for our app - we have been using the BUILDING documentation process for some time. However, now with the newest XCode (version 7.1) with Swift 2.1, the process is broken once again.

The following build commands failed:
    CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/iosrtcPlugin.swift
    CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginRTCTypes.swift
    CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginRTCPeerConnection.swift
    CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginRTCDataChannel.swift
    CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginMediaStreamTrack.swift
    CompileSwift normal i386 /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/ustyme/Plugins/cordova-plugin-iosrtc/PluginMediaStreamRenderer.swift
    CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler
(7 failures)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/cordova/build-debug.xcconfig,-project,ustyme.xcodeproj,ARCHS=i386,-target,ustyme,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/admin/github/ustyme/clients/alpha-ustyme/platforms/ios/cordova/build: Command failed with exit code 2

Sorry. I guess you can thank our friends in charge of Swift and Xcode...
